### ISSUE TITLE
日報の週シート生成がlamda上で失敗する原因を調査

### ISSUE THREAD

**Issue by 0g3** [ro-2020/ev3#35]

**Comment by 0g3** [comment]
sleep する時間を5sにいじってみたらいけた(lamdaのtestボタンで動いた）。

来週7/2にもう一度検証する

**Comment by 0g3** [comment]
## error log

### 6/24

```
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
wait: 10s
START RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13 Version: $LATEST
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0624」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/24 09:00:56 exit status 2
END RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13
REPORT RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13	Duration: 3975.01 ms	Billed Duration: 4000 ms Memory Size: 512 MB	Max Memory Used: 35 MB	
RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13 Process exited before completing request

createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0624」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc00020df88, 0xc000026178)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/24 09:00:59 exit status 2
START RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13 Version: $LATEST
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0624」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/24 09:02:03 exit status 2
END RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13
REPORT RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13	Duration: 5983.47 ms	Billed Duration: 6000 ms Memory Size: 512 MB	Max Memory Used: 36 MB	
RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13 Process exited before completing request

createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0624」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/24 09:02:07 exit status 2
START RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13 Version: $LATEST
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0624」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc00020df88, 0xc000026178)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/24 09:04:11 exit status 2
END RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13
REPORT RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13	Duration: 4169.72 ms	Billed Duration: 4200 ms Memory Size: 512 MB	Max Memory Used: 37 MB	
RequestId: 47c3feda-49de-430a-8c06-4f17c51a3d13 Process exited before completing request

createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0624」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/24 09:04:15 exit status 2
```

- 1回目のsleepが発生した段階でlambdaで指定した関数がもう一度実行されてしまっている
- その結果 `panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0624」はすでに存在しています。別の名前を入力してください。, badRequest` が発生している。


### 6/17

```
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
wait: 10s
START RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6 Version: $LATEST
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0617」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/17 09:00:56 exit status 2
END RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6
REPORT RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6	Duration: 3666.67 ms	Billed Duration: 3700 ms Memory Size: 512 MB	Max Memory Used: 35 MB	
RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6 Process exited before completing request

createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0617」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc00020df88, 0xc000026178)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/17 09:00:59 exit status 2
START RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6 Version: $LATEST
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0617」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/17 09:02:00 exit status 2
END RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6
REPORT RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6	Duration: 3551.35 ms	Billed Duration: 3600 ms Memory Size: 512 MB	Max Memory Used: 35 MB	
RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6 Process exited before completing request

createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0617」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/17 09:02:04 exit status 2
START RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6 Version: $LATEST
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0617」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc000235f88, 0xc000070058)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/17 09:04:15 exit status 2
END RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6
REPORT RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6	Duration: 3829.72 ms	Billed Duration: 3900 ms Memory Size: 512 MB	Max Memory Used: 35 MB	
RequestId: e9f3b6aa-28cb-4cf5-9993-6149319900d6 Process exited before completing request

createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0617」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:88 +0xcb6
main.nippo(0xc00023ff88, 0xc000026178)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:599 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:737 +0x58
2019/06/17 09:04:20 exit status 2
```

- 上と同じ原因っぽい。

**Comment by 0g3** [comment]
停止時間の問題かと思ったがちがうっぽい。

- 5s設定でこけていた(7/1)
- 上の5sで行けた例はlambdaのテストボタン実行だった

このことからcronでlambdaの実行を行うときにsleepを挟むとリスタートがかかる可能性があると推測できる。

## 7/1 error
```
release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
wait: 5s
START RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f Version: $LATEST
release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0701」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:89 +0xcb6
main.nippo(0xa5e6c0, 0xc00000e018)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:597 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:736 +0xb2
2019/07/01 09:00:56 exit status 2
END RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f
REPORT RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f	Duration: 4102.82 ms	Billed Duration: 4200 ms Memory Size: 512 MB	Max Memory Used: 37 MB	
RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f Process exited before completing request

release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0701」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:89 +0xcb6
main.nippo(0xa5e6c0, 0xc000090008)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:597 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:736 +0xb2
2019/07/01 09:01:00 exit status 2
START RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f Version: $LATEST
release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0701」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:89 +0xcb6
main.nippo(0xa5e6c0, 0xc00000e018)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:597 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:736 +0xb2
2019/07/01 09:02:02 exit status 2
END RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f
REPORT RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f	Duration: 4502.04 ms	Billed Duration: 4600 ms Memory Size: 512 MB	Max Memory Used: 37 MB	
RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f Process exited before completing request

release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0701」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:89 +0xcb6
main.nippo(0xa5e6c0, 0xc00000e018)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:597 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:736 +0xb2
2019/07/01 09:02:06 exit status 2
START RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f Version: $LATEST
release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0701」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:89 +0xcb6
main.nippo(0xa5e6c0, 0xc00000e018)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:597 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:736 +0xb2
2019/07/01 09:03:57 exit status 2
END RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f
REPORT RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f	Duration: 4438.22 ms	Billed Duration: 4500 ms Memory Size: 512 MB	Max Memory Used: 38 MB	
RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f Process exited before completing request

release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0701」はすでに存在しています。別の名前を入力してください。, badRequest

goroutine 1 [running]:
main.createNextSheet()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:89 +0xcb6
main.nippo(0xa5e6c0, 0xc00000e018)
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:597 +0xb8
main.main()
/Users/cr0w/dev/src/github.com/ro-2020/nippo/main.go:736 +0xb2
2019/07/01 09:04:00 exit status 2
```

## ☝️のエラーでリスタートがかかってる場所
```
release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
wait: 5s
START RequestId: ae5cd4d4-22af-4dd2-adc0-fc0ddb9f4a4f Version: $LATEST
release mode
createNextSheetはっじまるよ〜
create start 1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
1nI_qm4IdXpdPhqzoCtaCJwVsqVzheDrdsPXJbOaTaTA
panic: googleapi: Error 400: Invalid requests[0].updateSheetProperties: シート名「0701」はすでに存在しています。別の名前を入力してください。, badRequest
```

**Comment by 0g3** [comment]
これで動いた↓
https://github.com/ro-2020/nippo/commit/326ada7239038d470c3b110028f8d51b962c84f4
